# Generated by Django 5.1.4 on 2025-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sleeptime',
            field=models.DurationField(help_text='Número em horas'),
        ),
        migrations.AlterField(
            model_name='person',
            name='socialtime',
            field=models.DurationField(help_text='Número em horas'),
        ),
    ]
