# Generated by Django 5.1.4 on 2025-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_person_sleeptime_alter_person_socialtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
