# Generated by Django 5.1.4 on 2025-01-28 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_userresponse_delete_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User Response', 'verbose_name_plural': 'User Responses'},
        ),
        migrations.AddField(
            model_name='userresponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
