# Generated by Django 5.1.4 on 2025-01-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_userresponse_options_userresponse_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialtime', models.CharField(max_length=100)),
                ('sleeptime', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
